package com.hackathon.codewalker.model;

public record TutorialStep(
        String filePath,        // e.g., "src/main/java/Main.java"
        String elementFqn,      // e.g., "com.myapp.Main.processData" (The anchor)
        int fallbackLine,       // Line number backup if FQN fails
        String authorNote,      // "This method handles the retry logic"
        String aiExplanation    // The HTML generated by OpenAI
) {}